export enum BookMutation {
  SET_BOOKS = "SET_BOOKS",
  SET_IS_LOADING = "SET_IS_LOADING",
  SET_IS_ERROR = "SET_IS_ERROR",
  ADD_BOOK_TO_CART = "ADD_BOOK_TO_CART",
  REMOVE_BOOK_FROM_CART = "REMOVE_BOOK_FROM_CART",
}
